---
# Variable setup
- name: OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yaml"

# Setup/install tasks
- include_tasks: setup-RedHat.yaml
  when: ansible_os_family == 'RedHat'

# Tasks
- name: this copy file index.html
  template:
    src: templates/index.html
    dest: "{{ folder }}" 

- firewalld:
    port: 8081/tcp
    permanent: yes
    state: enabled
  notify: 
    - reload service firewalld

...
